version = 1

[global]
no_fp16 = false

[[game]]
exe = "benchmark"
multiplier = 4
flow_scale = 1.0
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "vkcube"
multiplier = 4
flow_scale = 0.7
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"
