[terminal.shell]
program = "/usr/bin/zsh"

[window]
dimensions = { columns = 110, lines = 35 }
opacity = 0.8
padding.x = 15
padding.y = 0
decorations = "Full" # "None"
decorations_theme_variant = "Dark" # "Light"
blur = false

[font]
normal = { family = "Cousine Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always"}
unfocused_hollow = true

[general]
live_config_reload = true

[terminal]

